### ISSUE TITLE
Closing angle bracket of an Object should also be indented

### ISSUE THREAD

**Issue by bwl21** [Phrogz/NeatJSON#11]
```json
{
   "a" : {
      "b" : 1,
      "c" : 2
   },
   "b" : {
      "b" : 1,
      "c" : 2
   }
}
```

Would e easier to read if the closing angle bracket is adjusted to the content

```json
{
   "a" : {
      "b" : 1,
      "c" : 2
       },
   "b" : {
      "b" : 1,
      "c" : 2
       }
}
```

**Comment by Phrogz** [comment]
This would be a reasonable formatting option, but not the only or default behavior.

Perhaps an option called `indentClose:true`?

**Comment by Phrogz** [comment]
I've added this feature as `indentLast` for JavaScript, `indent_last` for Ruby.

**Comment by Phrogz** [comment]
By the way, in case you haven't tried it, you might also prefer the "short" formatting mode (maybe along with some object/array padding). That makes it even easier to see where objects end.

**Comment by bwl21** [comment]
Thanks. Cool to make it an option.
