### ISSUE TITLE
Neatjson yields [] of object contains an empty Array and {} if object contains an emtpy Hash

### ISSUE THREAD

**Issue by bwl21** [Phrogz/NeatJSON#12]
The sumary says it all.

**Comment by Phrogz** [comment]
The summary is unclear. To file a bug report, please include actual code, what you expected as the output, and what you got instead.

I've just spent 15 minutes trying to figure out what bug you might be seeing, and I cannot reproduce anything that looks wrong. The following, for example, seems correct to me:

```js
$ node
x = require('./neatjson.js')
o = [1,[],2,{},[{}],{a:[]},[[]],{o:{}}]
console.log( x.neatJSON( o, { wrap:1, short:true } ) )
// [1,
//  [],
//  2,
//  {},
//  [{}],
//  {"a":[]},
//  [[]],
//  {"o":{}}]
```

```ruby
$ irb
require 'neatjson'
#=> true 

o = [ 1, [], 2, {}, [{}], {a:[]}, [[]], {o:{}} ]
puts JSON.neat_generate( o, wrap:1, short:true )
#=> [1,
#=>  [],
#=>  2,
#=>  {},
#=>  [{}],
#=>  {"a":[]},
#=>  [[]],
#=>  {"o":{}}]
```

**Comment by bwl21** [comment]
The issue occurs in the ruby version, not in the Javascript version. So you cannot reproduce it on http://phrogz.net/JS/neatjson/neatjson.html.

**Comment by bwl21** [comment]
I managed to reproduce the issiue with opal-rpl

install the opal gem:

gem install opal

```bash
test> opal-repl ../lib/neatjson.rb 
>> JSON.neat_generate([ 1, [], 2, {}, [{}], {a:[]}, [[]], {o:{}} ])
=> "[]"
>> JSON.neat_generate({a:{b:[]}})
=> "[]"
>> JSON.neat_generate({a:{b:{}}})
=> "{}"
>> JSON.neat_generate({a:{b:{a:1}}})
=> "{\"a\":{\"b\":{\"a\":1}}}"
>> JSON.neat_generate({a:{b:[1]}})
=> "{\"a\":{\"b\":[1]}}"
>> 
```
I need to work with the opal guys to make the test work

**Comment by bwl21** [comment]
I could boil it down to a pattern which reveals some different behavior between ruby and opal with respect of lambda vs proc (https://github.com/opal/opal/issues/260)

Is there a chance that you accept the PR (see commit 42bff09) such that neatjson also can be used with Opal?

**Comment by Phrogz** [comment]
Commit 0594535 should fix this problem for you for Opal
