### ISSUE TITLE
Would like to have an explicit control over sorting the keys

### ISSUE THREAD

**Issue by bwl21** [Phrogz/NeatJSON#16]
I would like to have explicit control about the order of the keys. I have implemented in https://github.com/bwl21/NeatJSON/tree/feature/explicit_sort.

It is controlled by options:

```explicit_sort: [[:e, :d,],[:b, :a]]}````

* the first array lists elements to be sorted at the beginning
* the second array lilsts elements to be sorted to the ends
* elements in none of the two lists are placed inbetween, either in input order or controlled by sort option.

This is the testcase

```ruby
	{value:{a:1, b:2, c:{a:1, b:2}, d: 3, e:4}, tests:[
		{ json:%Q{{"e":4,"d":3,"c":{"b":2,"a":1},"b":2,"a":1}}, 
                     opts:{wrap:false, explicit_sort: [[:e, :d,],[:b, :a]]} },
		{ json:%Q{{"e":4,"d":3,"b":2,"a":1,"c":{"b":2,"a":1}}}, 
                     opts:{wrap:false, explicit_sort: [[:e, :d,],[:b, :a, :c]]} },
		{ json:%Q{{
  "e":4,
  "d":3,
  "c":{
    "b":2,
    "a":1
  },
  "b":2,
  "a":1
}},
              opts:{wrap:1, explicit_sort: [[:e, :d,],[:b, :a]]} },
		{ json:%Q{{"e":4,
 "d":3,
 "c":{"b":2,
      "a":1},
 "b":2,
 "a":1}}, 
opts:{short:true, wrap:1, explicit_sort: [[:e, :d,],[:b, :a]]} }
	]}
```

I can prepare a pull request if you would be willing to integrate that. It depends/conflicts with  pr #15. So we should decide #15 one first.

**Comment by Phrogz** [comment]
The unlabeled "keys at beginning" and "keys at end" seems to specific to me. How about:

```js
opts:{ sort:function(key,value,object){ return someOrderingValue } }
```

in which case you can choose to create your own lookup that does what you want, or others can order based on value instead of key, etc.

**Comment by Phrogz** [comment]
I have added the `sort:lambda` feature in e85c1662fdd.

**Comment by bwl21** [comment]
Thanks for implementing this. The approach is more generic than mine and allows to achieve what I want.

But you introduced a new patten which I did not dare to do: options itself can no longer be expressed as JSON in all cases. I am not sure if this is a strong requirement, but I think it was at least a nice to have.

**Comment by bwl21** [comment]
Had another look into this. I would like to give my user full control over sorting. Therefore it is required, that the neatjson options can be represented as JSON.

I fully agree that the unlabeled keys are not very expressive.
```javascript
explicit_sort: {before:[:e, :d,], after[:b, :a]]}
```

You have renamed the option from  `sorted` to `sort`. Wouldn't it be better to keep the `sorted`and provide the `sort` as an extra option. In my approach, I could control the sorting of those keys which were not covered by the explicit_sort.

But my main concern is the fact that options can no longer be expressed as javascript.
