### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by gagan-bansal** [Phrogz/NeatJSON#17]
Very nice module, It would be nice if you publish the same on npm also.

**Comment by Phrogz** [comment]
Thank you for the compliment. I will consider creating a full NPM module from it.

**Comment by Phrogz** [comment]
Sorry for how long this took, but I finally added an npm module in e2a28c47957e4a0ad55e7c7e35e1536f6090b545.

**Comment by gagan-bansal** [comment]
Thanks, great!
