### ISSUE TITLE
Default sorting fails with on objects with mixed string/symbol keys

### ISSUE THREAD

**Issue by reidab** [Phrogz/NeatJSON#27]
Given an object like 

```ruby
{
  :a => 1,
  'b' => 2
}
```

Generating JSON with `sort: true` fails with `ArgumentError: comparison of Symbol with String failed`. This can be worked around by setting `sort: ->(k) { k.to_s }`, but it seems like it should be handled by default.

**Comment by Phrogz** [comment]
Thanks for the report! Fixed.
